name: gimp-edge
version: 2.9.3~git
#licence: $SNAP/gimp/src/LICENCE.txt
summary: GNU Image Manipulation Program - www.gimp.org
description: |
    A freely distributed program for such tasks as photo retouching, image
    composition and image authoring.  Whether you are a graphic designer,
    photographer,  illustrator,  or scientist,  GIMP provides you with
    sophisticated tools to get your job done.  You can further enhance your
    productivity with GIMP thanks to many customization options and 3rd party
    plugins.
confinement: devmode

apps:
    gimp:
        command: gimp

parts:
    glib:
        plugin: autotools
        #configflags:
        #filesets:
        source: git://git.gnome.org/glib
        source-type: git
        build-packages:
            - build-essential

    gdk-pixbuf:
        plugin: autotools
        #configflags:
        #filesets:
        source: git://git.gnome.org/gdk-pixbuf
        source-type: git
        build-packages:
            - build-essential

    babl: 
        after: [ glib, gdk-pixbuf ]
        plugin: autotools
        configflags: [ --disable-docs ]
        #filesets:
            #binaries:
            #headers:
        source: git://git.gnome.org/babl
        source-type: git
        build-packages:
            - autoconf
            - build-essential
            - dh-autoreconf
            - libgdk-pixbuf2.0-dev

    gegl:
        after: [ babl ]
        plugin: autotools
        configflags: [ --enable-gtk-doc-html=no --enable-workshop ]
        #filesets:
            #binaries:
            #headers:
        source: git://git.gnome.org/gegl
        source-type: git
        build-packages:
            - autoconf
            - build-essential
            - dh-autoreconf
            - libavcodec-dev
            - libavformat-dev
            - libavutil-dev
            - libcairo2-dev
            - libfontconfig1-dev
            - libfreetype6-dev
            - libgexiv2-dev
            - libgraphviz-dev
            - libjasper-dev
            - libjpeg-dev
            - libjson-glib-dev
            - liblensfun-dev
            - liblua5.2-dev         # ? Don't know what version is expected
            - libopenexr-dev
            - libpango1.0-dev
            - libpng12-dev          # ? Not sure about v1.2 vs v1.6
            - libraw-dev
            - librsvg2-dev
            - libsdl1.2-dev
            - libsdl2-dev
            - libspiro-dev
            - libtiff5-dev
            - libv4l-dev
            - libwebp-dev
            - lua5.2                # ?
            - python3-pydot
            - ruby
        #stage-packages:

    gimp:
        #after: [ babl, gegl, libmypaint ]
        plugin: autotools
        configflags: [ --disable-gtk-doc ]
        #filesets:
            #binaries:
            #headers:
        source: git://git.gnome.org/gimp
        source-type: git
        build-packages:
            - autoconf-archive
            - build-essential
            - libcdb-dev
            - dh-translations
            - docbook
            - docbook-dsssl
            - docbook-to-man
            - docbook-xml
            - docbook-xsl
            - gir1.2-gudev-1.0
            - gir1.2-poppler-0.18
            - gnome-common
            - gnome-pkg-tools
            - gtk-doc-tools
            - jade
            - libaa1-dev
            - libamd2.4.1
            - libart-2.0-dev
            - libbabl-0.1-0
            - libbabl-dev
            - libblas-common
            - libblas3
            - libbz2-dev
            - libcamd2.4.1
            - libccolamd2.9.1
            - libcholmod3.0.6
            - libcolamd2.9.1
            - libcups2-dev
            - libcupsfilters-dev
            - libcupsfilters1
            - libcupsimage2-dev
            - libcurl4-gnutls-dev
            - libdbus-glib-1-dev
            - libexif-dev
            - libffi-dev
            - libfontconfig1-dev
            - libgdk-pixbuf2.0-doc
            - libgegl-0.3-0         # ? Pretty sure not required, since building GEGL
            - libgegl-dev           # ? Not sure if unneeded
            - libgfortran3
            - libgs-dev
            - libgs9
            - libgs9-common
            - libgtk-3-dev          # ? Fairly sure GIMP is still gtk2
            - libgtk2.0-dev
            - libgtk2.0-doc
            - libgudev-1.0-dev
            - libidn11-dev
            - libijs-0.35
            - libijs-dev
            - libjbig2dec0
            - libjbig2dec0-dev
            - libjpeg-dev
            - liblapack3
            - libmng-dev
            - libpango1.0-dev
            - libpaper-dev
            - libpaper1
            - libpng12-dev          # ? Not sure about v1.2 vs v1.6
            - libpoppler-dev
            - libpoppler-glib-dev
            - libpoppler-glib8
            - libpoppler58
            - libpython-all-dev
            - librsvg2-dev
            - libsp1c2
            - libsuitesparseconfig4.4.6
            - libtiff5-dev
            - libumfpack5.7.1
            - libwebkit-dev
            - libwmf-dev
            - libxmu-dev
            - libxmu-headers
            - libxpm-dev
            - patchutils
            - pkg-config
            - poppler-data
            - python                # ? Not sure of how explicit dependencies need to be (popey naming g++ explicitly for instance) 
            - python-cairo-dev
            - python-gobject-2
            - python-gobject-2-dev
            - python-gtk2
            - python-gtk2-dev
            - python-pkg-resources
            - python-scour
            - python-six
            - python2.7-dev
            - sgml-data
            - xsltproc
            - zlib1g-dev
        stage-packages:
            - gimp-gmic

    libmypaint:
        #after: [ gegl ]
        plugin: autotools
        #filesets:
            #binaries:
            #headers:
        source: git://github.com/mypaint/libmypaint.git
        source-type: git
        build-packages:
            - build-essential
            - intltool
            - libjson-c-dev
            - liblcms2-dev
            - libpng12-dev          # ? Not sure about v1.2 vs v1.6
            - librsvg2-dev
            - python-gi
