name: gimp-git
version: 2.9.3~git
license: parts/gimp/build/src/LICENSE.txt
summary: GNU Image Manipulation Program - www.gimp.org
description: |
    A freely distributed program for such tasks as photo retouching, image
    composition and image authoring.  Whether you are a graphic designer,
    photographer,  illustrator,  or scientist,  GIMP provides you with
    sophisticated tools to get your job done.  You can further enhance your
    productivity with GIMP thanks to many customization options and 3rd party
    plugins.
confinement: devmode

apps:
    gimp:
        command: gimp-git

parts:
    babl: 
        plugin: autotools
        configflags: [ --disable-docs, --disable-shared ]
        #filesets:
        source: git://git.gnome.org/babl
        source-type: git
        build-packages:
            - autoconf
            - build-essential
            - dh-autoreconf
            - libgdk-pixbuf2.0-dev

    gegl:
        after: [ libmypaint, babl ]
        plugin: autotools
        configflags: [ --enable-gtk-doc-html=no, --disable-shared, --enable-workshop, --enable-binreloc ]
        #filesets:
            #babl:
                #- ./parts/install/babl/
        source: git://git.gnome.org/gegl
        source-type: git
        build-packages:
            - autoconf
            - build-essential
            - dh-autoreconf
            - libavcodec-dev
            - libavformat-dev
            - libavutil-dev
            - libcairo2-dev
            - libexiv2-dev
            - libfontconfig1-dev
            - libfreetype6-dev
            - libgexiv2-dev
            - libgraphviz-dev
            - libjasper-dev
            - libjpeg-dev
            - libjson-glib-dev
            - liblensfun-dev
            - liblua5.1-0-dev
            - libopenexr-dev
            - libpango1.0-dev
            - libpng12-dev
            - libraw-dev
            - librsvg2-dev
            - libsdl1.2-dev
            - libsdl2-dev
            - libspiro-dev
            - libtiff5-dev
            - libv4l-dev
            - libwebp-dev
            - lua5.1
            - python3-pydot
            - ruby
        #stage-packages:

    gimp:
        after: [ babl, gegl, libmypaint ]
        plugin: autotools
        configflags: [ --disable-gtk-doc, --disable-shared, --enable-binreloc, --disable-python ]
        #filesets:
            #gegl:
                #- ./parts/gegl/
        source: git://git.gnome.org/gimp
        source-type: git
        build-packages:
            - autoconf-archive
            - build-essential
            - dh-translations
            - docbook
            - docbook-dsssl
            - docbook-to-man
            - docbook-xml
            - docbook-xsl
            - gir1.2-gudev-1.0
            - gir1.2-poppler-0.18
            - gnome-common
            - gnome-pkg-tools
            - gtk-doc-tools
            - jade
            - libaa1-dev
            - libamd2.4.1
            - libart-2.0-dev
            - libbabl-0.1-0
            - libbabl-dev
            - libblas-common
            - libblas3
            - libbz2-dev
            - libcamd2.4.1
            - libccolamd2.9.1
            - libcdb-dev
            - libcholmod3.0.6
            - libcolamd2.9.1
            - libcups2-dev
            - libcupsfilters-dev
            - libcupsfilters1
            - libcupsimage2-dev
            - libcurl4-gnutls-dev
            - libdbus-glib-1-dev
            - libexif-dev
            - libffi-dev
            - libfontconfig1-dev
            - libgdk-pixbuf2.0-doc
            - libgfortran3
            - libgs-dev
            - libgs9
            - libgs9-common
            - libgtk2.0-dev
            - libgtk2.0-bin
            - libgtk2.0-doc
            - libgudev-1.0-dev
            - libidn11-dev
            - libijs-0.35
            - libijs-dev
            - libjbig2dec0
            - libjbig2dec0-dev
            - libjpeg-dev
            - liblapack3
            - libmng2
            - libmng-dev
            - libpango1.0-dev
            - libpaper-dev
            - libpaper1
            - libpng12-dev
            - libpoppler-dev
            - libpoppler-glib-dev
            - libpoppler-glib8
            - libpoppler58
            - libpython-dev
            - libpython2.7-dev
            - librsvg2-dev
            - libsp1c2
            - libsuitesparseconfig4.4.6
            - libtiff5-dev
            - libumfpack5.7.1
            - libwebkit-dev
            - libwmf-dev
            - libxmu-dev
            - libxmu-headers
            - libxpm-dev
            - patchutils
            - pkg-config
            - poppler-data
            - python-cairo-dev
            - python-gobject-2
            - python-gobject-2-dev
            - python-gtk2-dev
            - python-pkg-resources
            - python-scour
            - python-six
            - python2.7-dev
            - sgml-data
            - xsltproc
            - zlib1g-dev
        stage-packages:
            - gimp-gmic

    libmypaint:
        after: [ babl ]
        plugin: autotools
        source: git://github.com/mypaint/libmypaint.git
        source-type: git
        build-packages:
            - build-essential
            - intltool
            - libjson-c-dev
            - liblcms2-dev
            - libpng12-dev
            - librsvg2-dev
            - python-gi
