# plank snap-package config
# Copyright (C) 2016 Michael Hall <mhall119@ubuntu.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
name: plank
version: 0.11.2-snap1
summary: Plank is meant to be the simplest dock on the planet.
description: The goal is to provide just what a dock needs and absolutely nothing more. It is, however, a library which can be extended to create other dock programs with more advanced features.
confinement: strict

apps:
  plank:
    command: bin/plank.run
    plugs: [x11, unity7, home, network]

parts:
  plank:
    plugin: autotools
    source: https://git.launchpad.net/plank
    source-type: git
    configflags: [ --prefix=/usr ]
    build-packages: 
        - gettext
        - intltool
        - valac
        - libbamf3-dev
        - libcairo2-dev
        - libdbusmenu-gtk3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libglib2.0-dev
        - libgtk-3-dev
        - libwnck-3-dev
    stage-packages:
        - libcairo2
        - libgee-0.8-2
        - libglib2.0-0
        - libgtk-3-0
        - libpango-1.0-0
        - libpangocairo-1.0-0
        - libwnck-3-0
        - libbamf3-2
    
  launcher:
    plugin: copy
    files:
      launcher: bin/plank.run

