name: plank
version: "0.11.2-snap1"
summary: Plank is meant to be the simplest dock on the planet.
description: |
  The goal is to provide just what a dock needs and absolutely nothing more.
  It is, however, a library which can be extended to create other dock
  programs with more advanced features.
confinement: strict

apps:
  plank:
    command: bin/plank.run
    plugs: [x11, unity7, home, network]

parts:
  plank:
    source: https://git.launchpad.net/plank.git
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages: 
        - gettext
        - intltool
        - valac
        - libbamf3-dev
        - libcairo2-dev
        - libdbusmenu-gtk3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libglib2.0-dev
        - libgtk-3-dev
        - libwnck-3-dev
    stage-packages:
        - libcairo2
        - libgee-0.8-2
        - libglib2.0-0
        - libgtk-3-0
        - libpango-1.0-0
        - libpangocairo-1.0-0
        - libwnck-3-0
        - libbamf3-2
  launcher:
    plugin: copy
    files:
      launcher: bin/plank.run

