name: nginx
version: "1.11.1"
summary: nginx is an HTTP and reverse proxy server
description: |
  nginx ("engine x") is an HTTP and reverse proxy server, a mail proxy server,
  and a generic TCP/UDP proxy server, originally written by Igor Sysoev.  For a
  long time, it has been running on many heavily loaded Russian sites including
  Yandex, Mail.Ru, VK, and Rambler.
confinement: devmode

apps:
  nginx:
    command: nginx
    stop-command: nginx -s quit
    daemon: simple
    plugs: [network, network-bind]

parts:
  nginx:
    source: http://hg.nginx.org/nginx/archive/cb783d9cc197.tar.gz
    plugin: autotools
    #configflags:
      #- --sbin-path=
      #- --conf-path=
      #- --pid-path=
      #- --error-log-path=
      #- --http-log-path=
      #- --user=
      #- --group=
      #- --with-/without-/select_module
      #- --with-/without-/poll_module
      #- --without-http_gzip_module
      #- --without-http_rewrite_module
      #- --without-http_proxy_module
      #- --with-http_ssl_module
      #- --with-pcre=
      #- --with-pcre-jit
      #- --with-zlib=#zlib lib source
      #- --with-cc-opt=#other CFLAGS
      #- --with-ld-opt=#for use with BSD(?)
    organize:
      parts/nginx/src/auto: parts/nginx/src/
    build-packages:
      - build-essential
      - autoconf
      - dh-autoreconf
      - libpcre2-posix0
      - libpcre3
      - libpcre3-dev
      - pcre2-utils
      - pcredz
      - pcregrep
      - zlib1g
      - zlib1g-dev
    #stage-packages:
    
#Preparing to pull nginx 
#Pulling nginx 
#Preparing to build nginx 
#Building nginx 
#autoreconf -i
#autoreconf: 'configure.ac' or 'configure.in' is required
#Command '['/bin/sh', '/tmp/tmpbm__y22a', 'autoreconf', '-i']' returned
#non-zero exit status 1
#Command '['lxc', 'exec', 'snapcraft-nonmonarchically-wurtzitic-eddie',
#'--', 'snapcraft', 'snap', '--output', 'nginx_1.11.1_amd64.snap']'
#returned non-zero exit status 1

    #### The problem is that `configure` is hidden one extra directory below
    #### where it should be:
    ####     parts/nginx/src/auto/   and not
    ####     parts/nginx/src/        where it should be
