[Icon Theme]
Name=LoginIcons
Comment=Special icons for the Ubuntu login experience
Inherits=Humanity,Adwaita,hicolor

Example=directory-x-normal

#Directory list
Directories=apps/16,apps/22,apps/24,apps/48,apps/64

[apps/16]
Size=16
Context=Applications
Type=Fixed

[apps/22]
Size=22
Context=Applications
Type=Fixed

[apps/24]
Size=24
Context=Applications
Type=Fixed

[apps/48]
Size=48
Context=Applications
Type=Scalable

[apps/64]
Size=64
Context=Applications
Type=Fixed

