#!/bin/sh

root_dir=`pwd`

for dir in `find * -type d`; do
    echo "Testing $dir"
    cd ${root_dir}/$dir
    docker run -v $(pwd):/snapcraft -t sergiusens/snapcraft sh -c "cd /snapcraft && snapcraft"
done
