name: nginx
version: "1.11.1"
summary: nginx is an HTTP and reverse proxy server
description: |
  nginx ("engine x") is an HTTP and reverse proxy server, a mail proxy
  server, and a generic TCP/UDP proxy server, originally written by Igor
  Sysoev.  For a long time, it has been running on many heavily loaded
  Russian sites including Yandex, Mail.Ru, VK, and Rambler.
confinement: devmode

apps:
  nginx:
    command: nginx
    plugs: [ network, home ]

parts:
  nginx:
    source: http://nginx.org/download/nginx-1.11.1.tar.gz
    plugin: autotools


