name: nginx
version: 1.10
summary: nginx is an HTTP and reverse proxy server
description: |
    nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server,
    and a generic TCP/UDP proxy server, originally written by Igor Sysoev.  For
    a long time, it has been running on many heavily loaded Russian sites
    including Yandex, Mail.Ru, VK, and Rambler.  According to Netcraft, nginx
    served or proxied 27.24% busiest sites in May 2016.
confinement: devmode

apps:
    nginx:
        command: nginx
        plugs: [ network, home ]

parts:
    nginx:
        plugin: autotools
        source: http://nginx.org/download/nginx-1.10.1.tar.gz
        source-type: tar

