#!/bin/sh -x
ARCH="x86_64-linux-gnu"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/pulseaudio:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/dri:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/qt5/libs:$LD_LIBRARY_PATH"
export QT_PLUGIN_PATH="$SNAP/usr/lib/$ARCH/qt5/plugins"
export XDG_DATA_HOME="$SNAP/usr/share"
export FONTCONFIG_PATH="$SNAP/etc/fonts/config.d"
export FONTCONFIG_FILE="$SNAP/etc/fonts/fonts.conf"
export XKB_CONFIG_ROOT="$SNAP/usr/share/X11/xkb"
# Mesa Libs
export LD_LIBRARY_PATH=$SNAP/usr/lib/$ARCH/mesa:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$SNAP/usr/lib/$ARCH/mesa-egl:$LD_LIBRARY_PATH
# Tell libGL where to find the drivers
export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/$ARCH/dri

# ensure that our HW/opengl libs are before the snap specific libs
export LD_LIBRARY_PATH=$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH

export LIBGL_DEBUG="verbose"
env
# copy example config into place if it doesn't exist already
if [ ! -f $SNAP_USER_DATA/minetest.conf ];
then
  echo "No $SNAP_USER_DATA/minetest.conf found, will copy before launch"
  cp $SNAP/minetest.conf.example $SNAP_USER_DATA/minetest.conf
else
  echo "$SNAP_USER_DATA/minetest.conf found, launching"
fi

$SNAP/bin/minetest --config $SNAP_USER_DATA/minetest.conf --logfile $SNAP_USER_DATA/minetest.log $*
