name: arduino
version: 1.8.4
summary: Arduino IDE
description: Open-source electronics prototyping platform
confinement: strict
grade: stable

apps:
    arduino:
        command: desktop-launch ${SNAP}/arduino-snap
        plugs: [x11, unity7, home, network, serial-port]
    builder:
        command: arduino-builder

parts:
    libxtst:
        plugin: nil
        stage-packages:
            - libxtst6
        prime:
            - usr/lib/*-linux-gnu/libXtst.so.6
            - usr/lib/*-linux-gnu/libXtst.so.6.1.0
    upstream:
        source: https://www.arduino.cc/download.php?f=/arduino-1.8.4-linux64.tar.xz
        source-type: tar
        plugin: dump
        prime:
            - -install.sh
            - -uninstall.sh
            - -java/lib/ext/jfxrt.jar
            - -java/lib/jfxswt.jar
            - -java/lib/*/libjfxwebkit.so
            - -java/lib/*/libjfxmedia.so
        after: [libxtst, desktop-gtk2]
    launcher:
        plugin: dump
        source: .
        prime:
            - arduino-snap
    desktop-gtk2:
        prime:
            - -usr/share/icons/*
            - -usr/lib/x86_64-linux-gnu/libicu-*
            - -usr/lib/x86_64-linux-gnu/libLLVM-*
 
