name: snapcraft
version: daily
summary: Snapcraft enables you to build snaps
description: |
 Snapcraft helps you assemble a whole project in a single tree out of many
 pieces. It can drive a very wide range of build and packaging systems, so that
 you can simply list all the upstream projects you want and have them built and
 installed together as a single tree.
confinement: devmode

apps:
  snapcraft:
    command: usr/bin/snapcraft
    plugs: [home, network, network-bind]

parts:
  snapcraft:
    plugin: python3
    source: https://github.com/ubuntu-core/snapcraft.git
    build-packages:
      - bash-completion
      - dh-python
      - pkg-config
      - python3
      - python3-apt
      - python3-docopt
      - python3-fixtures
      - python3-jsonschema
      - python3-lxml
      - python3-magic
      - python3-petname
      - python3-pkg-resources
      - python3-progressbar
      - python3-requests
      - python3-requests-oauthlib
      - python3-requests-toolbelt
      - python3-responses
      - python3-setuptools
      - python3-testscenarios
      - python3-testtools
      - python3-xdg
      - python3-yaml
      - squashfs-tools
    stage-packages:
      - python3-apt
      - python3-docopt
      - python3-jsonschema
      - python3-lxml
      - python3-magic
      - python-magic
      - python3-petname
      - python3-pkg-resources
      - python3-progressbar
      - python3-requests
      - python3-requests-oauthlib
      - python3-requests-toolbelt
      - python3-ssoclient
      - python3-xdg
      - python3-yaml
      - squashfs-tools
      - sudo
      - python3
      - libmagic1
      - lxd
