name: qdriverstation
version: 16.06.1
summary: Open source clone of the FRC Driver Station
description: The QDriverStation is a cross-platform and open-source alternative to the FRC Driver Station. It supports the FRC 2009-2014 communication protocol and the FRC 2015-2016 protocol.
confinement: devmode

apps:
  qdriverstation:
    command: desktop-launch qdriverstation

parts:
  qdriverstation:
    source: https://github.com/FRC-Utilities/QDriverStation.git
    plugin: qmake
    qt-version: qt5
    build-packages:
      - libsdl2-dev
      - qttools5-dev 
      - build-essential
      - libqt5webkit5-dev 
      - qtmultimedia5-dev
      - qtdeclarative5-dev 
      - qttools5-dev-tools 
    after: [desktop/qt5]
  env:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libqt5gui5
      - libqt5qml5
      - libqt5quick5
      - libqt5widgets5
      - libqt5network5
      - libqt5multimedia5
      - libqt5declarative5
      - qml-module-qtquick2
      - qml-module-qtquick-window2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-controls
      - qml-module-qt-labs-settings
    after: [qdriverstation]

