name: ubuntukylin-icon-theme
version: "1.0"
summary: Remixed icon theme based on Square-Light, Ultra-Flat and ubuntu-mono.
description: |
  Remixed icon theme based on Square-Light, Ultra-Flat and ubuntu-mono.  After
  installations run the activation command to enable it.

  Activation command: ubuntukylin-icon-theme.enable

  After that, you should find ubuntukylin-icon-theme-snap in your favourite
  theme editor (eg. unity-tweak-tool).
confinement: devmode

apps:
  enable: 
   command: "cp -r $SNAP/icon-theme/ubuntukylin-icon-theme-snap /home/$USER/.icons/ubuntukylin-icon-theme-snap"
   plugs: [home]
  set:
    command: "desktop-launch gsettings set org.gnome.desktop.interface icon-theme 'ubuntukylin-icon-theme-snap'"
    plugs: [home, gsettings]
  disable: 
    command: "rm -rf /home/$USER/.icons/ubuntukylin-icon-theme-snap && desktop-launch gsettings reset org.gnome.desktop.interface icon-theme"
    plugs: [home, gsettings]

parts:
  theme:
    source: lp:ubuntukylin-theme
    plugin: copy_and_edit
    files:
      ubuntukylin-icon-theme: icon-theme/ubuntukylin-icon-theme-snap
    edit:
      ubuntukylin-icon-theme/index.theme:
        "Name=.*$": "Name=ubuntukylin-icon-theme-snap"
    stage-packages:
      - gsettings-desktop-schemas
    after: [desktop/glib-only]
