#!/bin/sh
# Wrapper to direct datadir and config dir to writable paths by default.
# This is still overridable (only last argument is taken) by the command
# line user entry.
# Handle special cases like --help <subcommand>.

if [ $# -gt 0 ]; then
  commandoption="$1"
  shift
fi

if [ "$commandoption" = "--help" ] && [ $# -gt 0 ]; then
  subcommand="$1"
  shift
fi

exec consul $commandoption $subcommand -data-dir $SNAP_USER_DATA/data -config-dir $SNAP_USER_DATA/config.d "$@"
