name: consul
version: "0.6.4"
summary: Consul is a tool for service discovery, monitoring and configuration
description: |
  Consul is distributed, highly available, and extremely scalable.
  Consul provides service discovery, health checking, key/value storage and
  multi-datacenter.

apps:
  consul:
    command: bin/consul
    plugs: [network, network-bind]

parts:
  consul:
    plugin: go
    source: https://github.com/hashicorp/consul
    go-importpath: github.com/hashicorp/consul
