name: otter-browser  # the name of the snap
version: 0.9.11-dev  # the version of the snap
summary: Classic Opera (12.x) UI using Qt5  # 79 char long summary
description: Project aiming to recreate the best aspects of the classic Opera (12.x) UI using Qt5  
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
    otter-app:
        command: desktop-launch otter-browser
        plugs: [x11, unity7, opengl, network, browser-support, pulseaudio]

parts:
    otter: 
        source: https://github.com/OtterBrowser/otter-browser.git
        plugin: cmake
        build-packages: 
        - libqt5webkit5-dev
        - libqt5xmlpatterns5-dev
        - qtmultimedia5-dev
        - qtdeclarative5-dev
        - qtbase5-dev 
        stage-packages:
        - libqt5gui5
        - libcanberra-gtk-module
        - overlay-scrollbar
        after: [desktop-qt5]
