name: leafpad
version: 1
summary: GTK+ based simple text editor
description: |
   Leafpad is a simple GTK+ based text editor, the user interface is similar
   to Notepad. It aims to be lighter than GEdit and KWrite, and to be as
   useful as them.
confinement: devmode

apps:
  leafpad:
    command: gtk-launch leafpad
    plugs: [home, unity7, opengl, network, x11]

parts:
  leafpad:
    plugin: autotools
    source: https://github.com/oluc/leafpad
    source-type: git
    snap:
      - -usr/share/doc
    after: [gtkconf]
    stage-packages:
      - fontconfig-config

build-packages:
  - build-essential
  - libgtk2.0-dev
  - intltool
