name: nginx
version: master
summary: HTTP, reverse proxy, mail proxy and a generic TCP/UDP proxy server.
description: |
  nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server,
  and a generic TCP/UDP proxy server, originally written by Igor Sysoev.

grade: devel
confinement: strict

apps:
  nginx:
    command: nginx
    plugs: [network, network-bind]

parts:
  nginx:
    source: http://hg.nginx.org/nginx
    source-type: mercurial
    plugin: autotools
