name: etherpad-lite-unofficial
version: 0.1
summary: Etherpad-lite, really-real time collaborative editor
description: | 
  Etherpad allows you to edit documents collaboratively in real-time, much like
  a live multi-player editor that runs in your browser. Write articles, press
  releases, to-do lists, etc. together with your friends, fellow students or
  colleagues, all working on the same document at the same time.
confinement: devmode

apps:
  etherpad-lite:
    command: bin/runpad
    daemon: simple
    plugs: [network, network-bind]

parts:
  etherpad-lite:
    plugin: nodejs
    source: git://github.com/ether/etherpad-lite
    source-subdir: src
    build-packages:
      - gzip
      - git
      - curl
      - python
      - libssl-dev
      - pkg-config
      - build-essential
  etherpad-lite-settings:
    plugin: copy
    source: git://github.com/ether/etherpad-lite
    files:
      settings.json.template: etc/settings.json
  wrapper-and-config:
    plugin: make
    source: .
