name: etherpad-lite-unofficial
version: 0.1
summary: Etherpad-lite, eally-real time collaborative editor # 79 char long summary
description: Etherpad is a really-real time collaborative editor maintained by the Etherpad Community # A longer description for the snap
confinement: devmode

apps:
  etherpad-lite:
    command: bin/runpad
    daemon: simple
    plugs: [network, network-bind]

parts:
  etherpad-lite:
    plugin: nodejs
    source: git://github.com/ether/etherpad-lite
    source-subdir: src
    build-packages:
      - gzip
      - git
      - curl
      - python
      - libssl-dev
      - pkg-config
      - build-essential
  etherpad-lite-settings:
    plugin: copy
    source: git://github.com/ether/etherpad-lite
    files:
      settings.json.template: etc/settings.json
  wrapper-and-config:
    plugin: make
    source: .
