name: etherpad-lite-unofficial # the name of the snap
version: 0.1 # the version of the snap
# The vendor for the snap (replace 'Vendor <email@example.com>')
# vendor: Winael <vinzjobard@ubuntu.com>

summary: Etherpad-lite, eally-real time collaborative editor # 79 char long summary
description: Etherpad is a really-real time collaborative editor maintained by the Etherpad Community # A longer description for the snap
icon: icon.png # A path to an icon for the package

parts:
  etherpad-lite:
    plugin: nodejs
    source: git://github.com/ether/etherpad-lite
    source-subdir: src
    stage-packages: 
      - gzip 
      - git 
      - curl 
      - python 
      - libssl-dev 
      - pkg-config 
      - build-essential