name: jtiledownloader
version: "0.6.1"
summary: A Java application for downloading OpenStreetMap tiles 
description: |
 jTileDownloader allows downloading OpenStreetMap files for offline
 map caching
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
    jtiledownloader:
        command: bin/launcher

parts:
    jtiledownloader:
        plugin: copy
        source:  http://svn.openstreetmap.org/applications/utils/downloading/JTileDownloader/trunk/release/jTileDownloader-0-6-1.zip
        files:
            "*": .
        stage-packages: [openjdk-8-jre, openjdk-8-demo]
    launcher:
        plugin: copy
        files:
            launcher: bin/launcher
