name: pluma
version: 1.15.0~git
summary: official text editor of the MATE desktop environment
description: |
 Pluma is a text editor which supports most standard editor features,
 extending this basic functionality with other features not usually
 found in simple text editors. Pluma is a graphical application which
 supports editing multiple text files in one window (known sometimes as
 tabs or MDI).

apps:
  pluma:
    command: gtk-launch pluma
    plugs:
      - home
      - unity7
      - x11

parts:
  mate-common:
    plugin: autotools
    source: https://github.com/mate-desktop/mate-common.git
    build-packages:
      - gettext
      - intltool
      - libtool
      - pkg-config
    install-via: prefix

  mate-desktop:
    after:
      - mate-common
    plugin: autotools
    source: https://github.com/mate-desktop/mate-desktop.git
    source-type: git
#    source-tag: mate-desktop-1.15.0
    configflags:
      - --disable-mpaste
      - --disable-schemas-compile
      - --disable-silent-rules
      - --disable-static
      - --with-gtk=3.0
    build-packages:
      - gobject-introspection
      - gtk-doc-tools
      - intltool
      - libdconf-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libglib2.0-doc
      - libgtk-3-dev
      - libgtk-3-doc
      - libstartup-notification0-dev
      - libxml2-dev
    install-via: prefix
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libstartup-notification0
      - libxml2
      - hicolor-icon-theme

  pluma:
    after:
      - mate-desktop
      - gtkconf
    plugin: autotools
    source: https://github.com/mate-desktop/pluma.git
    source-type: git
    #source-tag: pluma-1.15.0
    configflags:
      - --disable-python
      - --without-matedesktop
      - --with-gtk=3.0
    build-packages:
      - gettext
      - gtk-doc-tools
      - intltool
      - iso-codes
      - libenchant-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libgtksourceview-3.0-dev
      - mate-common
      - libxml2-dev
      - yelp-tools
    install-via: prefix
    stage-packages:
      - dconf-gsettings-backend
      - iso-codes
      - libglib2.0-0
      - libgtk-3-0
      - libpango-1.0-0
      - libgdk-pixbuf2.0-0

#  integration:
#    plugin: nil
#    stage-packages:
#      - dmz-cursor-theme
#      - light-themes
#      - ttf-ubuntu-font-family
#      - ubuntu-mate-icon-themes
#      - ubuntu-mate-themes
#    snap:
#      - usr/share
#      - -usr/share/doc
