name: cloudfoundry-cli
version: 6.19.0
summary:  The official command line client for Cloud Foundry.
description: |
  A tool to deploy and manage Cloud Foundry applications.
confinement: strict

apps:
  cf:
    command: bin/main
    plugs: [network, network-bind]

parts:
    cli:
      plugin: cf
      source: https://github.com/cloudfoundry/cli
      source-type: git
      source-tag: v6.19.0
      go-importpath: github.com/cloudfoundry/cli
      build-packages: [g++]
