name: kodi  # the name of the snap
version: "16.1-Jarvis"  # the version of the snap, which can be any string
summary: Kodi Media Center  # 79 char long summary
description: |
  Kodi, formerly known as XBMC Media Center, is an award winning free and
  open source software media-player and entertainment hub for all your digital
  media. Kodi is available for Linux, Mac OS X (Leopard, Tiger and Apple TV)
  and Microsoft Windows, as well as the original Xbox game console. Created in
  2003 by a group of like minded programmers, Kodi is a non-profit project run
  and developed by volunteers located around the world. More than 50 software
  developers have contributed to Kodi, and 100-plus translators have worked to
  expand its reach, making it available in more than 30 languages.
confinement: devmode  # start with devmode, then use "strict" to enforce system
                      # access only via declared interfaces

apps:
  kodi:
    command: wrapper_kodi.sh
    plugs:
      - unity7
      - network
      - network-bind
      - home
      - opengl
      - pulseaudio
      - mount-observe
      - optical-drive
      - camera
  kodi-standalone:
    command: wrapper_kodi-standalone.sh
    plugs:
      - unity7
      - network
      - network-bind
      - home
      - opengl
      - pulseaudio
      - mount-observe
      - optical-drive
      - camera

parts:
  kodi:
    source: https://github.com/xbmc/xbmc.git
    source-tag: 16.1-Jarvis
    plugin: x_kodiautotools
    configflags:
      - --prefix=/
    build-packages:
      - automake
      - bison
      - build-essential
      - cmake
      - curl
      - cvs
      - default-jre
      - fp-compiler
      - gawk
      - gdc
      - gettext
      - git-core
      - gperf
      - libasound2-dev
      - libass-dev
      - libboost-dev
      - libbluetooth-dev
      - libbz2-dev
      - libcap-dev
      - libcdio-dev
      - libcurl3
      - libcurl4-openssl-dev
      - libcpluff0-dev
      - libcrossguid-dev
      - libdbus-1-dev
      - libdvdread-dev
      - libfontconfig1-dev
      - libegl1-mesa-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libgif-dev
      - libglew-dev
      - libiso9660-dev
      - libjasper-dev
      - libjpeg-dev
      - liblzo2-dev
      - libmicrohttpd-dev
      - libmpeg2-4-dev
      - libmodplug-dev
      - libmysqlclient-dev
      - libnfs-dev
      - libogg-dev
      - libpcre3-dev
      - libplist-dev
      - libpng12-dev
      - libpulse-dev
      - libsdl2-dev
      - libsmbclient-dev
      - libsqlite3-dev
      - libssh-dev
      - libssl-dev
      - libtiff5-dev
      - libtinyxml-dev
      - libtool
      - libudev-dev
      - libusb-dev
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxml2-dev
      - libxmu-dev
      - libxrandr-dev
      - libxrender-dev
      - libxslt1-dev
      - libxt-dev
      - libyajl-dev
      - mesa-utils
      - nasm
      - pmount
      - python-dev
      - python-imaging
      - python-sqlite
      - swig
      - unzip
      - uuid-dev
      - yasm
      - zip
      - zlib1g-dev
      - autopoint
      - libltdl-dev
      - libtag1-dev
    stage-packages:
      - libasound2
      - libass5
      - libavahi-client3
      - libavahi-common3
      - libbluetooth3
      - libbz2-1.0
      - libc6
      - libcdio13
      - libcurl3
      - libcrossguid0
      - libdbus-1-3
      - libdrm2
      - libexpat1
      - libfreetype6
      - libfribidi0
      - libgcc1
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglew1.13
      - libgmp10
      - libgnutls30
      - libjpeg8
      - liblzma5
      - liblzo2-2
      - libmicrohttpd10
      - libmpeg2-4
      - libmysqlclient20
      - libogg0
      - libpcre3
      - libpcrecpp0v5
      - libpng12-0
      - libpulse0
      - libpython2.7
      - libsdl2-2.0-0
      - libsmbclient
      - libsqlite3-0
      - libssh-4
      - libstdc++6
      - libtag1v5
      - libtiff5
      - libtinyxml2.6.2v5
      - libudev1
      - libva-x11-1
      - libva1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libx11-6
      - libxext6
      - libxml2
      - libxrandr2
      - libxslt1.1
      - libyajl2
      - zlib1g
    snap:
      - -bin/kodi
      - -bin/kodi-standalone
      - -bin/xbmc
      - -bin/xbmc-standalone
    after: [libdvdcss2, wrappers-copy, libdcadec]
  libdvdcss2:
    source: https://code.videolan.org/videolan/libdvdcss.git
    source-tag: 1.4.0
    plugin: autotools
    build-packages:
      - automake
      - git-core
      - build-essential
    stage-packages:
      - libc6
  libdcadec:
    source: https://github.com/foo86/dcadec.git
    source-tag: v0.2.0
    plugin: make
    make-parameters:
      - PREFIX=
    build-packages:
      - automake
      - git-core
      - build-essential
    stage-packages:
      - libc6
  wrappers-copy:
    plugin: copy
    files:
      wrapper_kodi.sh: bin/wrapper_kodi.sh
      wrapper_kodi-standalone.sh: bin/wrapper_kodi-standalone.sh
