name: kpcli-elopio
version: "3.0"
summary: KeePass Command Line Interface
description: |
  A command line interface (interactive shell) to work with KeePass 
  1.x or 2.x database files.
confinement: devmode

apps:
  kpcli:
    command: scripts/run.sh

parts:
  kpcli:
    source: https://github.com/alecsammon/kpcli.git
    plugin: copy
    files:
      kpcli.pl: scripts/kpcli.pl
    stage-packages:
      - perl-base
      - libcrypt-rijndael-perl
      - libterm-readkey-perl
      - libsort-naturally-perl
      - libfile-keepass-perl
      - libterm-shellui-perl
      - libterm-readline-gnu-perl
      - libclone-perl
  launcher:
    plugin: copy
    files:
      run.sh: scripts/run.sh
