name: ristretto
version: 1
summary: lightweight picture-viewer for the Xfce desktop environment
description: |
  Ristretto is a fast and lightweight picture-viewer for the Xfce desktop
  environment.

confinement: devmode

apps:
  ristretto:
    command: usr/bin/ristretto.wrapper
    plugs: [home, network, unity7, x11]

parts:
  ristretto:
    source: git://git.xfce.org/apps/ristretto
    source-type: git
    plugin: autotools
    configflags:
      - --enable-maintainer-mode  # so src/marshal.h gets generated
  env:
    plugin: copy
    files:
      wrapper: usr/bin/ristretto.wrapper
    stage-packages:
      - fontconfig-config
      - fonts-freefont-ttf
      - hicolor-icon-theme
      - libglib2.0-bin
      - libgtk2.0-bin
      - shared-mime-info
      - tumbler

build-packages:
  - exo-utils
  - libdbus-glib-1-dev
  - libexif-dev
  - libexo-1-dev
  - libgtk2.0-dev
  - libxfce4ui-1-dev
  - intltool
  - xfce4-dev-tools
